
disabled_rules: # rule identifiers to exclude from running
#  - cyclomatic_complexity
#  - file_length
#  - function_body_length
#  - line_length
  - todo
#  - trailing_whitespace
#  - type_body_length
#  - variable_name
#  - unused_closure_parameter
#  - nesting
opt_in_rules:
  - empty_count
excluded:
  - Pods

trailing_comma:
  mandatory_comma: true
# reporter: "checkstyle"
